sudo: false

language: node_js

include: &toolchain_linux_amd64
  node_js:
  - '10'
  - '9'
  - '8'
  - '6'
  os: linux
  dist: trusty
  addons:
    apt:
      update: true
      packages:
        - libgtk-3-dev
        - gcc-5
        - xvfb
        - at-spi2-core
  before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - export CC="gcc-5"

include: &toolchain_linux_386
  node_js:
  - '10'
  - '9'
  - '8'
  - '6'
  os: linux
  dist: trusty

  addons:
    apt:
      packages:
		- gcc-5
        - xvfb
		- gcc-multilib
        - g++-multilib
        - libgtk-3-dev:i386
        # the rest fixes broken dependencies of libgtk:i386
        - libgirepository-1.0-1:i386
        - libglib2.0-dev:i386
        - gir1.2-glib-2.0:i386
        - gir1.2-atk-1.0:i386
        - libatk1.0-dev:i386
        - libfreetype6-dev:i386
        - libfontconfig1-dev:i386
        - libcairo2-dev:i386
        - libgdk-pixbuf2.0-dev:i386
        - libpango1.0-dev:i386
        - libxft-dev:i386
        - libpng12-dev:i386
  before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - export CC="gcc-5"

include: &toolchain_osx_amd64
  node_js:
  - '10'
  - '9'
  - '8'
  - '6'
  os: osx
  osx_image: xcode8
  before_install:
  - brew update
  - brew upgrade python
  - pip3 install click pyobjc-framework-Quartz


# Travis CI build matrix.
# Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
    - env: arch=amd64
      <<: *toolchain_linux_amd64
    - env: arch=386
      <<: *toolchain_linux_386
    - env: arch=amd64
      <<: *toolchain_osx_amd64

after_script:
  - (cd tests/_snapshots && ../../node_modules/.bin/now --public --token "$NOW_TOKEN")

before_deploy:
  - npm run rebuild
  - ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`$arch`.tar.gz"
  - cd $TRAVIS_BUILD_DIR && tar -czvf $ARCHIVE_NAME ui.node && cd -

deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    branch: master
    tags: true
    node: '10'
  api_key:
    secure: kkdWKa9iqJNKrfvW1pLgVx0EUBGcx+VGOzKG7xvxSfpNudZpuoGjWL4p9fQQD5TRELGwY7KCpFfZPbp2dnHQ9z82lW2XmnEC+bcskmfO/PXLJi3uyLrEY7iBwR3UhiWSdKRaPptfnndQrC21jmlweJNMCTWW8VqgvYupYITf9mfIq0WbEmFMeXJr7KzRO1yX4uAOOqnSTb60uRSrg+9V000cmDi246ir2ApaRw6NBOmI2v0kbirdbDe/vcAclgD2K0CFV7h8HIucbiU1DWBF2aQY3u5II4mItM4yskv0BmOr4vxXR0+7B/iysZNjWtXLbt4CiekvQKADUqPFpPk33LTjPxtAzdUYhHaoGTwchCIpkJG32KqTBL1+9h2I8WyhB3tKgxbFTZynkBihS2mYJad+rdO2RCXZtFZxf9bPWv6+PGelKnTFFBR9gPGTha4FeIeYZyuxuecAE7I+0UhS+wvwls3Xstro9fw+OwyvTysMEWOrjm1DvBuZyNnkqcfBKt3q4MOZsEHFnTEu6A1htr96FutAj/vap0e1RMokhMSIbe/hwq3whmELzWpRkOVDPEZfN47PCYc3f/UfYf0RMSWthibZOD30IX3207LsOgxZXfH3PDVcG9q0lvowGKWMcKy7d6+VVqgE97Aq7i07fizbpMWbNY7cStNy26m6IxM=

env:
  global:
    - secure: XqGG2yBs4womFTlobjnnGOumI8IvIfRa8QglBytg7ASMeVVd2v2/5zkI5B2i+ESdxH7iaTIzDKicLbQ9ZxhUbENE6cgDSsAqFnarSm3bWHatsBidiIHumSlM7jifnLSXr5rjKThdLRDvSSj4lMqYF7m1e50Leta3Ux1qMzfIe8H6VhEOg9ZIsVuq7eR/3nF29SH60z97GxvoFu4azFsfsHLInGZqGH7wVRz8mmRBDfhnBYvzl6fitY1DO3xpKSyuCfp8PrscgNz6MJPSl2QZbiw2JvY6FUwjzKiYD+TBA/LZzUEmU08Z+X033qJaqrtDoG+RI5dDhVvBfa2k5zz1IJPTlOb/r8lHzPrEoZKTdLD9n/FGG4+KHnLUa6ZNxtLU9ena/MAjZKTtonWbGMPa/sCLYW/ETw5PM2u9unPIbiomkGa+Ym7RYyO9q3KbUd+jki5re+rKxspJU5Aagjq1S+2DLEuBehLHd69bLT78Epb1o5oyuvTKRTdcJMfeN0gWMt3Mo4K3UhMbRSs3HBRjvwzLTAh/L7LOoFNTO29zQd2KZOpy9BuacmtiofqqEPyr9ShoKgO2hg+cJZcD/G1J9oVksWb/EUl4597nNAS9WFl0eA/sfYCtRoR6+qZ1O2vmfOJkUTOalyez6S2sYJBn4JPFnG43ysxHDonY37173SE=
