build: false

skip_branch_with_pr: true

image: Visual Studio 2017

environment:
  nodejs_version: "10"

configuration: Release
platform: x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - if defined APPVEYOR_REPO_TAG_NAME (
      npm run rebuild &&
      7z a -ttar %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar libui.node &&
      7z a -tgzip %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar.gz %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar
    )

artifacts:
  - path: '**\*.tar.gz'

deploy:
  - provider: GitHub
    artifact: /.*\.gz/
    draft: false
    prerelease: true
    auth_token:
      secure: eMIAnmLDhZy2Sq/UAXB50fYr1C2BugaafN8XiV6Wur8wMvPLXWIuCKU7Jt/Y9Of6
    on:
      appveyor_repo_tag: true
