build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release
platform:
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - 7z a -ttar %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar node_libui.node
  - 7z a -tgzip %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar.gz %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar

artifacts:
  - path: '**\*.tar.gz'

deploy:
  - provider: GitHub
    artifact: /.*\.gz/
    draft: false
    prerelease: true
    auth_token:
      secure: eMIAnmLDhZy2Sq/UAXB50fYr1C2BugaafN8XiV6Wur8wMvPLXWIuCKU7Jt/Y9Of6
    on:
      appveyor_repo_tag: true
      nodejs_version: "Current"
