build: false

skip_branch_with_pr: true

image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"

configuration: Release
platform: x64

install:
  - ps: Install-Module nvm -Scope CurrentUser -Force
  - ps: Install-NodeVersion $env:nodejs_version
  - ps: Set-NodeVersion $env:nodejs_version
  - ps: node --version
  - ps: npm --version
  - ps: npm install

test_script:
  - ps: node --version
  - ps: npm --version
  - ps: npm test

after_test:
  - if defined APPVEYOR_REPO_TAG_NAME (
      7z a -ttar %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar node_libui.node &&
      7z a -tgzip %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar.gz %APPVEYOR_REPO_TAG_NAME%-win-%PLATFORM%.tar
    )

artifacts:
  - path: '**\*.tar.gz'

deploy:
  - provider: GitHub
    artifact: /.*\.gz/
    draft: false
    prerelease: true
    auth_token:
      secure: eMIAnmLDhZy2Sq/UAXB50fYr1C2BugaafN8XiV6Wur8wMvPLXWIuCKU7Jt/Y9Of6
    on:
      appveyor_repo_tag: true
      nodejs_version: "10"
